# -*- coding: utf-8 -*-
"""Lab#3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6x1bIndgSgrlNXtO_F2LrsVxdbwifnX
"""

!pip install pandasql

import os

filenames = ["departuredelays.csv", "housing.csv", "sf-airbnb.csv", "owid-covid-data.csv"]

for fname in filenames:
    for root, dirs, files in os.walk("/content"):
        if fname in files:
            print(f"✅ Found: {os.path.join(root, fname)}")

import pandas as pd

df_delays  = pd.read_csv("/content/sample_data/departuredelays.csv")
df_housing = pd.read_csv("/content/housing.csv")
df_airbnb  = pd.read_csv("/content/sample_data/sf-airbnb.csv")
df_covid   = pd.read_csv("/content/sample_data/owid-covid-data.csv")

for name, df in [("Delays", df_delays), ("Housing", df_housing),
                  ("Airbnb", df_airbnb), ("Covid", df_covid)]:
    print(f"\n{'='*50}")
    print(f"{name} — Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print(df.head(2))

# ============================================================
# Lab Activity 3
# ============================================================

import pandas as pd
import pandasql as ps
import json
import os

print("=" * 60)
print("SECTION 1: Loading Datasets")
print("=" * 60)

df_delays  = pd.read_csv("/content/sample_data/departuredelays.csv")
df_housing = pd.read_csv("/content/housing.csv")
df_airbnb  = pd.read_csv("/content/sample_data/sf-airbnb.csv")
df_covid   = pd.read_csv("/content/sample_data/owid-covid-data.csv")

print(f"✅ Delays  : {df_delays.shape}")
print(f"✅ Housing : {df_housing.shape}")
print(f"✅ Airbnb  : {df_airbnb.shape}")
print(f"✅ Covid   : {df_covid.shape}")


# ============================================================
# SECTION 2: DATA PREPROCESSING
# ============================================================

print("\n" + "=" * 60)
print("SECTION 2: Data Preprocessing")
print("=" * 60)

# ---------- 2A. Check Missing Values ----------
print("\n[Delays] Missing values:")
print(df_delays.isnull().sum())

print("\n[Housing] Missing values:")
print(df_housing.isnull().sum())

print("\n[Airbnb] Missing values (selected columns):")
airbnb_cols = ['property_type', 'room_type', 'neighbourhood_cleansed',
               'price', 'bedrooms', 'bathrooms', 'review_scores_rating']
print(df_airbnb[airbnb_cols].isnull().sum())

print("\n[Covid] Missing values (selected columns):")
covid_cols = ['continent', 'location', 'date', 'total_cases',
              'new_cases', 'total_deaths', 'people_vaccinated']
print(df_covid[covid_cols].isnull().sum())

# ---------- 2B. Drop Missing Values ----------
df_delays_clean  = df_delays.dropna()
df_housing_clean = df_housing.dropna()
df_airbnb_clean  = df_airbnb[airbnb_cols].dropna()
df_covid_clean   = df_covid[covid_cols].dropna()

print(f"\n[Delays]  Before: {len(df_delays):,}  | After: {len(df_delays_clean):,}")
print(f"[Housing] Before: {len(df_housing):,} | After: {len(df_housing_clean):,}")
print(f"[Airbnb]  Before: {len(df_airbnb):,}  | After: {len(df_airbnb_clean):,}")
print(f"[Covid]   Before: {len(df_covid):,} | After: {len(df_covid_clean):,}")

# ---------- 2C. Select Columns ----------
print("\n[Delays] Selected columns:")
df_delays_sel = df_delays_clean[['date', 'delay', 'distance', 'origin', 'destination']]
print(df_delays_sel.head(3))

print("\n[Housing] Selected columns:")
df_housing_sel = df_housing_clean[['housing_median_age', 'median_income',
                                    'median_house_value', 'ocean_proximity']]
print(df_housing_sel.head(3))

print("\n[Airbnb] Selected columns:")
print(df_airbnb_clean.head(3))

print("\n[Covid] Selected columns:")
print(df_covid_clean.head(3))

# ---------- 2D. Filtering ----------
# Flights with actual delays (> 0 minutes)
df_delayed = df_delays_clean[df_delays_clean['delay'] > 0]
print(f"\n[Delays] Flights with delay > 0: {len(df_delayed):,}")

# Houses valued above $200,000
df_expensive = df_housing_clean[df_housing_clean['median_house_value'] > 200000]
print(f"[Housing] Houses above $200,000: {len(df_expensive):,}")

# Airbnb listings with rating >= 90
df_top_airbnb = df_airbnb_clean[df_airbnb_clean['review_scores_rating'] >= 90]
print(f"[Airbnb] Listings rated >= 90: {len(df_top_airbnb):,}")

# Covid records with new_cases > 0
df_active_covid = df_covid_clean[df_covid_clean['new_cases'] > 0]
print(f"[Covid] Records with new_cases > 0: {len(df_active_covid):,}")

# ---------- 2E. Basic Statistics ----------
print("\n[Delays] Delay stats:")
print(df_delays_clean['delay'].describe())

print("\n[Housing] House value stats:")
print(df_housing_clean['median_house_value'].describe())

print("\n[Airbnb] Review score stats:")
print(df_airbnb_clean['review_scores_rating'].describe())

print("\n[Covid] Total cases stats:")
print(df_covid_clean['total_cases'].describe())


# ============================================================
# SECTION 3: ADVANCED SQL QUERIES (pandasql)
# ============================================================

print("\n" + "=" * 60)
print("SECTION 3: Advanced SQL Queries")
print("=" * 60)

# Rename for SQL use
df_delays_sql  = df_delays_clean
df_housing_sql = df_housing_clean
df_airbnb_sql  = df_airbnb_clean
df_covid_sql   = df_covid_clean

# ---- Query 1: Top 5 most frequent Origin Airports ----
q1 = """
    SELECT origin, COUNT(*) AS flight_count
    FROM df_delays_sql
    GROUP BY origin
    ORDER BY flight_count DESC
    LIMIT 5
"""
top5_origins = ps.sqldf(q1, locals())
print("\n[Query 1] Top 5 Most Frequent Origin Airports:")
print(top5_origins.to_string(index=False))

# ---- Query 2: Top 5 Ocean Proximity Categories ----
q2 = """
    SELECT ocean_proximity, COUNT(*) AS count
    FROM df_housing_sql
    GROUP BY ocean_proximity
    ORDER BY count DESC
    LIMIT 5
"""
top5_proximity = ps.sqldf(q2, locals())
print("\n[Query 2] Top 5 Ocean Proximity Categories (Housing):")
print(top5_proximity.to_string(index=False))

# ---- Query 3: Top 5 most frequent Airbnb Property Types ----
q3 = """
    SELECT property_type, COUNT(*) AS count
    FROM df_airbnb_sql
    GROUP BY property_type
    ORDER BY count DESC
    LIMIT 5
"""
top5_property = ps.sqldf(q3, locals())
print("\n[Query 3] Top 5 Most Frequent Airbnb Property Types:")
print(top5_property.to_string(index=False))

# ---- Query 4: Top 5 most frequent Airbnb Room Types ----
q4 = """
    SELECT room_type, COUNT(*) AS count
    FROM df_airbnb_sql
    GROUP BY room_type
    ORDER BY count DESC
    LIMIT 5
"""
top5_rooms = ps.sqldf(q4, locals())
print("\n[Query 4] Top 5 Most Frequent Airbnb Room Types:")
print(top5_rooms.to_string(index=False))

# ---- Query 5: Top 5 Locations by Total COVID Cases ----
q5 = """
    SELECT location, MAX(total_cases) AS max_total_cases
    FROM df_covid_sql
    GROUP BY location
    ORDER BY max_total_cases DESC
    LIMIT 5
"""
top5_covid = ps.sqldf(q5, locals())
print("\n[Query 5] Top 5 Locations by Total COVID Cases:")
print(top5_covid.to_string(index=False))

#---- Query 6: Top 5 Origins with Highest Average Delay ----
q6 = """
    SELECT origin, ROUND(AVG(delay), 2) AS avg_delay
    FROM df_delays_sql
    WHERE delay > 0
    GROUP BY origin
    ORDER BY avg_delay DESC
    LIMIT 5
"""
top5_avg_delay = ps.sqldf(q6, locals())
print("\n[Query 6] Top 5 Origins with Highest Average Delay (min):")
print(top5_avg_delay.to_string(index=False))


print("\n" + "=" * 60)
print("SECTION 4: Writing Results to External Storage")
print("=" * 60)

os.makedirs("/content/output", exist_ok=True)

top5_origins.to_csv("/content/output/top5_origins.csv", index=False)
top5_proximity.to_csv("/content/output/top5_ocean_proximity.csv", index=False)
top5_property.to_csv("/content/output/top5_airbnb_property.csv", index=False)
top5_covid.to_csv("/content/output/top5_covid_locations.csv", index=False)
print("✅ CSV files saved to /content/output/")

top5_origins.to_json("/content/output/top5_origins.json", orient="records", indent=2)
top5_proximity.to_json("/content/output/top5_ocean_proximity.json", orient="records", indent=2)
top5_property.to_json("/content/output/top5_airbnb_property.json", orient="records", indent=2)
top5_covid.to_json("/content/output/top5_covid_locations.json", orient="records", indent=2)
print("✅ JSON files saved to /content/output/")

with open("/content/output/summary_report.txt", "w") as f:
    f.write("=" * 60 + "\n")
    f.write("LAB ACTIVITY 1 - SUMMARY REPORT\n")
    f.write("=" * 60 + "\n\n")

    f.write("DATASET 1: Departure Delays\n")
    f.write(f"  Total records  : {len(df_delays_clean):,}\n")
    f.write(f"  Delayed flights: {len(df_delayed):,}\n")
    f.write(f"  Avg delay (delayed only): {df_delayed['delay'].mean():.2f} min\n\n")
    f.write("Top 5 Most Frequent Origin Airports:\n")
    f.write(top5_origins.to_string(index=False) + "\n\n")
    f.write("Top 5 Origins - Highest Avg Delay:\n")
    f.write(top5_avg_delay.to_string(index=False) + "\n\n")

    f.write("DATASET 2: California Housing\n")
    f.write(f"  Total records: {len(df_housing_clean):,}\n\n")
    f.write("Top 5 Ocean Proximity Categories:\n")
    f.write(top5_proximity.to_string(index=False) + "\n\n")

    f.write("DATASET 3: SF Airbnb\n")
    f.write(f"  Total records: {len(df_airbnb_clean):,}\n\n")
    f.write("Top 5 Property Types:\n")
    f.write(top5_property.to_string(index=False) + "\n\n")
    f.write("Top 5 Room Types:\n")
    f.write(top5_rooms.to_string(index=False) + "\n\n")

    f.write("DATASET 4: COVID-19 Data\n")
    f.write(f"  Total records: {len(df_covid_clean):,}\n\n")
    f.write("Top 5 Locations by Total Cases:\n")
    f.write(top5_covid.to_string(index=False) + "\n")

print("✅ TXT report saved to /content/output/summary_report.txt")

print("\n" + "=" * 60)
print("✅ Lab Activity Complete! Check /content/output/ folder.")
print("=" * 60)

from google.colab import files

files.download("/content/output/summary_report.txt")
files.download("/content/output/top5_origins.csv")
files.download("/content/output/top5_ocean_proximity.csv")
files.download("/content/output/top5_airbnb_property.csv")
files.download("/content/output/top5_covid_locations.csv")